default:
    just --list


# Run the server in swc mode
run_server:
    nest start -b swc

watch_server:
    nest start -b swc -w --type-check

lint:
    pnpm run lint 

prettier:
    pnpm exec prettier . --write

test:
    pnpm npx jest